version: '2.1'

services:

    producer:
        build:
            context: ./producer
        volumes:
            - producer-sync:/opt/app:nocopy
        networks:
            - app-network
        environment:
            - MESSAGE_QUEUE=amqp://rabbitmq
        links:
            - rabbitmq

    rabbitmq:
        image: rabbitmq:3.7.4
        ports:
            - "5672:5672"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    producer-sync:
        external: true
